
CONFIG:
  # 取值 mdb、project，演示时，设置为 project
  MODE: 'mbd'
  # 使用哪个模型，取值 YOLOV5
  MODEL: 'YOLOV5'
  # 使用哪个显卡
  DEVICE: 'cpu'


YOLOV5:
  # 模型文件
  WEIGHT: './weights/yolov5s.yaml/weights/best.pt'
  # 阈值
  CONF: 0.4
  # 过滤类别
  CLASSES: None





